### ISSUE TITLE
scaffolded helm chart: add podmonitor/prometheusrule (optional)

### ISSUE THREAD

**Issue by cbarbian-sap** [SAP/component-operator-runtime#101]
The scaffolded helm chart (./scaffold/templates/chart) should be able to optionally render a `PodMonitor` object such as

```yaml
{{- if .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "xxx.fullname" . }}
  labels:
    {{- include "xxx.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "xxx.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
{{- end }}
```

and a `PrometheusRule` object such as

```yaml
{{- if and .Values.metrics.prometheusRule.enabled .Values.metrics.prometheusRule.rules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "xxx.fullname" . }}
  labels:
    {{- include "xxx.labels" . | nindent 4 }}
spec:
  groups:
  - name: {{ include "xxx.name" . }}
    rules:
    {{- toYaml .Values.metrics.prometheusRule.rules | nindent 4 }}
{{- end }}
```
